### ISSUE TITLE
GitLab MR URL missing group/org

### ISSUE THREAD

**Issue by P15223971** [shiraji/find-pull-request#125]
Hi - would it be possible to add a field in the plugin options to insert a GitLab group/org? e.g. www.gitlab.com/example/........

At the moment, the plugin is able to find the MR but is missing the group part of the URL. 

If there was a field in the plugin options that would allow you to specify the group (e.g. 'example' as above) and then inject that into the MR URL obtained by the plugin, it would be very useful.

Thanks

**Comment by shiraji** [comment]
I tried to find merge request in one of my gitlab org. It successfully browsed to this URL. `https://gitlab.com/[org name]/[repo name]/merge_requests/347`

Are you using gitlab in your own domain? I thought gitlab does not start with "www".

**Comment by shiraji** [comment]
Are you taking about subgroups? https://about.gitlab.com/solutions/subgroups/

Is this the reason that gitlab redirect 

`https://gitlab.com/[org name]/[repo name]/merge_requests/347`

to 

`https://gitlab.com/[org name]/[repo name]/-/merge_requests/347`

relate to #126

**Comment by shiraji** [comment]
If this is subgroups, could you give me more details? I have no idea how subgroups works.

As far as I understand, subgroup can be nested, if `subgroup-1/subgroup-2` exists and a user X is in that group,

1. `https://gitlab.com/[org name]/[repo name]/subgroup-1/subgroup-2/merge_requests/1` is the correct URL for X not `https://gitlab.com/[org name]/[repo name]/merge_requests/1`
1. X's git config URL is `https://gitlab.com/[org name]/[repo name].git` or `git@gitlab.com:[org name]/[repo name].git`
1. No git config command give us info that X is in `subgroup-1/subgroup-2`

**Comment by shiraji** [comment]
And group...damn it. I don't know anything about gitlab...

https://gitlab.com/gitlab-org/secure/onboarding/-/merge_requests/39
SSH: `git@gitlab.com:gitlab-org/secure/onboarding.git`
HTTPS: `https://gitlab.com/gitlab-org/secure/onboarding.git`
MR URL template: `https://gitlab.com/[org name]/[group name]/[repository name]-/merge_requests/[merge request #]`

It seems git config contains group name. This plugin did not expect this URL format, thou.

**Comment by shiraji** [comment]
I released 1.7.1 now. Could you update this plugin to see if it resolve this problem. I close this issue for now.  Please feel free to reopen this issue if the version still have this problem.

Thank you very much for reporting issue!

**Comment by P15223971** [comment]
Wow thank you so much for the quick response and fix! I've just update the plugin and it's working fine now. Thanks again!
