### ISSUE TITLE
Option to open the main PR page instead of the files page

### ISSUE THREAD

**Issue by gmolau** [shiraji/find-pull-request#140]
The plugin currently takes you to the files list of a PR, e.g. `github.com/user/repo/pull/123/files`. I'm more often interested in the discussion though, e.g. `github.com/user/repo/pull/123`. It would be great if there were an option to open it instead.

Either way, thanks for the neat plugin!

**Comment by shiraji** [comment]
Ah, that's great idea. 

At this moment, this plugin has setting "Jump to File" as a default.

![image](https://github.com/shiraji/find-pull-request/assets/3675458/cd25ab0d-ebe1-44b1-8b6d-4d2979ec1ada)

If this setting is uncheck this plugin should jump to discussion page, instead. Let's me implement that.

**Comment by shiraji** [comment]
Yes, it is released in March 5th. 

https://plugins.jetbrains.com/plugin/8262-find-pull-request/edit/versions/stable/498300

Could you check if it works for you?

**Comment by gmolau** [comment]
I saw the update, but since then I can no longer invoke the plugin via the command palette, it only takes me to the plugins settings page, but doesn't expose the actual functionality anymore.

![Screenshot 2024-03-11 at 13 54 38](https://github.com/shiraji/find-pull-request/assets/23221000/7e12823d-6a18-430e-901a-97969b5de54b)
![Screenshot 2024-03-11 at 13 56 41](https://github.com/shiraji/find-pull-request/assets/23221000/999170e5-7735-46df-a3f7-9c831f905f6f)

**Comment by shiraji** [comment]
It was changed to "Pull Request"

https://github.com/shiraji/find-pull-request/blob/main/website/images/find-pr.gif

**Comment by shiraji** [comment]
but then, you are right, this seems not looks good. I never thought command palette

![image](https://github.com/shiraji/find-pull-request/assets/3675458/3dcdf0bd-4bbe-4582-bfef-abe1f81311de)

**Comment by shiraji** [comment]
move to #157

**Comment by gmolau** [comment]
Ok that works, thanks for adding this 👍
