### ISSUE TITLE
The action "Pull Request" is not easy to find from cmd+shift+a

### ISSUE THREAD

**Issue by shiraji** [shiraji/find-pull-request#157]
![image](https://github.com/shiraji/find-pull-request/assets/3675458/09801add-7453-4149-8d10-958083007d26)

**Comment by gmolau** [comment]
Maybe something like "Go to Pull Request", so that it doesn't sound like you are trying to open a new PR?

**Comment by shiraji** [comment]
Next version should fix this problem.

Now all menu except editor popup (right click), it looks something like "Go to Pull Request page".

![image](https://github.com/shiraji/find-pull-request/assets/3675458/625bdb06-092b-4871-b1f9-da03ea0e868c)

You can still be able to find "Find Pull Request"

![image](https://github.com/shiraji/find-pull-request/assets/3675458/01221270-fa4e-4238-9198-dfd2a28bd558)

I will release this version from now. it will be public within JetBrains's 2 business days.

**Comment by shiraji** [comment]
I think v2.0.2 fix this problem. I will close this issue for now. Feel free to reopen this issue if you have any problem.
