### ISSUE TITLE
Improvement: If PR was not found dialog should be shown, not popup.

### ISSUE THREAD

**Issue by jinek** [shiraji/find-pull-request#99]
If PR was not found dialog should be shown, not popup as popup requires to take the mouse.
Popup/Dialog should be under options.

![image](https://user-images.githubusercontent.com/10516222/63202555-77d55400-c08a-11e9-9390-5efa1f2e8c26.png)

**Comment by shiraji** [comment]
Are you saying you want to disable only "PR was not found" popup?

**Comment by shiraji** [comment]
Are you saying this plugin needs some other dialog options for "PR was not found"?

IntelliJ only supports these notification types

https://github.com/JetBrains/intellij-community/blob/4999f5293e4307870020f1d0d672a3d35a52f22d/platform/platform-api/src/com/intellij/notification/NotificationDisplayType.java

I don't want to create a custom dialog that is really hard to disable/enable by users.

**Comment by jinek** [comment]
No need for custom. My point was to make it possible to navigate using keyboard only. I will check whether rider support navigation to popup using keyboard and if no, will request the feature from them. I think this one is clear and can be closed.

**Comment by shiraji** [comment]
Thanks for reporting. In case they say there is a way to do so, please reopen this issue.
